[package]
name = "cjdns-nameserver"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { workspace = true }
eyre = { workspace = true}
rand = { workspace = true }
hex = { workspace = true }
hickory-client = { workspace = true }
base64 = { workspace = true }
hickory-server = { workspace = true }
serde = { workspace = true }
serde_yaml = { workspace = true }
tokio = { workspace = true }
async-trait = { workspace = true }

cjdns-keys = { workspace = true }
cjdns-bytes = { workspace = true }
cjdns-eth-rpc = { workspace = true }