[package]
name = "cjdns-bencode"
version = "0.1.0"
authors = [
    "Alex Kordys <a.kordys@mixbytes.io>"
]
edition = "2018"
license = "GPL-3.0-or-later"
description = "cjdns Bencode library"

[dependencies]
bendy = { workspace = true }
hex = { workspace = true }
serde = { workspace = true }
