[package]
name = "cjdns-util-http"
version = "0.1.0"
edition = "2021"

[dependencies]
serde = { workspace = true }
warp = { workspace = true }
anyhow = { workspace = true }
serde_json = { workspace = true }